#!/usr/bin/env python3
"""
Generate sprite_lookup.c by scanning ACTUAL sprite files on disk.
Also cross-references pokemon_database.c to get dex numbers and names.
Uses 'p' prefix to avoid grit symbol collisions.
"""

import re
import os
import sys

def scan_sprites_on_disk(sprites_dir):
    """
    Scan gfx/sprites/ for actual .c files and build a list of all sprites.
    Separates normal vs shiny based on _shiny suffix.
    Returns dict: { base_name: { 'normal': True/False, 'shiny': True/False } }
    e.g. { '0003': {'normal':True, 'shiny':True},
           '0003a': {'normal':True, 'shiny':True},
           '0869aa': {'normal':True, 'shiny':True} }
    """
    if not os.path.exists(sprites_dir):
        print(f"❌ Sprites directory not found: {sprites_dir}")
        return {}

    sprites = {}

    for f in os.listdir(sprites_dir):
        if not f.lower().endswith('.c'):
            continue

        name = f.replace('.c', '')

        # Is it a shiny file?
        is_shiny = name.endswith('_shiny')
        if is_shiny:
            base = name.replace('_shiny', '')
        else:
            base = name

        # Strip 'p' prefix if present (converter already added it)
        if base.startswith('p'):
            base = base[1:]

        # Must start with a digit (skip any non-sprite files)
        if not base or not base[0].isdigit():
            continue

        if base not in sprites:
            sprites[base] = {'normal': False, 'shiny': False}

        if is_shiny:
            sprites[base]['shiny'] = True
        else:
            sprites[base]['normal'] = True

    return sprites


def parse_pokemon_database(filepath):
    """
    Parse pokemon_database.c to build a lookup: filename_base -> {id, name}
    e.g. '0003' -> {id: 3, name: 'Venusaur'}
         '0003a' -> {id: 3, name: 'Mega Venusaur'}
    """
    print(f"📖 Reading {filepath}...")

    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Match: {ID, "Name", ..., "FILENAME.png", ...}
    # The PNG field is after 12 comma-separated fields
    pattern = r'\{\s*(\d+)\s*,\s*"([^"]+)"\s*,\s*[^,]+(?:,[^,]+){9},\s*"([^"]+\.png)"'
    matches = re.findall(pattern, content)

    db = {}
    for dex_id, name, png_filename in matches:
        base = png_filename.replace('.png', '').replace('.PNG', '')
        # Don't overwrite — first occurrence wins (base form before variants)
        if base not in db:
            db[base] = {'id': int(dex_id), 'name': name}

    print(f"   Database entries: {len(db)}")
    return db


def split_base_and_suffix(name):
    """
    Split '0003a' into ('0003', 'a')
    Split '0869aa' into ('0869', 'aa')
    Split '0201' into ('0201', '')
    """
    match = re.match(r'^(\d+)([a-z]*)$', name)
    if match:
        return match.group(1), match.group(2)
    return name, ''


def generate(sprites_on_disk, db_lookup):
    """Build the complete sprite_lookup.c content."""

    lines = []

    # ── header ──────────────────────────────────────────────────
    lines.append("// Auto-generated sprite lookup table")
    lines.append("// Generated by scanning gfx/sprites/ directory")
    lines.append("// DO NOT EDIT MANUALLY")
    lines.append("")
    lines.append('#include "sprite_lookup.h"')
    lines.append("")
    lines.append("// External sprite data declarations")
    lines.append("// These match the symbols generated by grit (with 'p' prefix)")
    lines.append("")

    # Sort sprites naturally (by number then suffix)
    sorted_sprites = sorted(sprites_on_disk.keys(),
                            key=lambda x: (int(re.match(r'(\d+)', x).group(1)),
                                           x[len(re.match(r'(\d+)', x).group(1)):]))

    # ── extern declarations ────────────────────────────────────
    for base in sorted_sprites:
        info = sprites_on_disk[base]
        sym = f"p{base}"

        if info['normal']:
            lines.append(f"extern const unsigned int {sym}Tiles[];")
            lines.append(f"extern const unsigned short {sym}Pal[];")
        if info['shiny']:
            lines.append(f"extern const unsigned int {sym}_shinyTiles[];")
            lines.append(f"extern const unsigned short {sym}_shinyPal[];")

    lines.append("")

    # ── lookup table ────────────────────────────────────────────
    lines.append("const SpriteLookupEntry SPRITE_LOOKUP[] = {")

    entry_count = 0
    missing_from_db = []

    for base in sorted_sprites:
        info = sprites_on_disk[base]
        sym = f"p{base}"

        num_part, suffix = split_base_and_suffix(base)
        suffix_c = 'NULL' if suffix == '' else f'"{suffix}"'

        # Get name from database
        if base in db_lookup:
            name = db_lookup[base]['name']
            dex_id = db_lookup[base]['id']
        else:
            # Not in database — use the number as dex ID, mark as unknown
            dex_id = int(num_part)
            name = f"Unknown ({base})"
            missing_from_db.append(base)

        # Normal entry
        if info['normal']:
            lines.append(f"    {{{dex_id}, {suffix_c}, 0, {sym}Tiles, {sym}Pal}}, // {name}")
            entry_count += 1

        # Shiny entry
        if info['shiny']:
            lines.append(f"    {{{dex_id}, {suffix_c}, 1, {sym}_shinyTiles, {sym}_shinyPal}}, // {name} (shiny)")
            entry_count += 1

    lines.append("};")
    lines.append("")
    lines.append(f"// Total entries: {entry_count}")

    return '\n'.join(lines), entry_count, missing_from_db


def main():
    print("=" * 60)
    print("Pokemon Sprite Lookup Generator")
    print("=" * 60)
    print()

    # ── find directories ────────────────────────────────────────
    sprites_dir = None
    for candidate in ['gfx/sprites', '../gfx/sprites']:
        if os.path.exists(candidate):
            sprites_dir = candidate
            break

    if not sprites_dir:
        print("❌ gfx/sprites/ not found!")
        print("   Run this from your Build folder.")
        sys.exit(1)

    db_path = None
    for candidate in ['source/pokemon_database.c', 'pokemon_database.c', '../source/pokemon_database.c']:
        if os.path.exists(candidate):
            db_path = candidate
            break

    if not db_path:
        print("❌ pokemon_database.c not found!")
        sys.exit(1)

    # ── scan & parse ────────────────────────────────────────────
    print(f"🔍 Scanning sprites in: {sprites_dir}")
    sprites_on_disk = scan_sprites_on_disk(sprites_dir)
    print(f"   Sprites on disk: {len(sprites_on_disk)}")
    print()

    db_lookup = parse_pokemon_database(db_path)
    print()

    # ── generate ────────────────────────────────────────────────
    content, entry_count, missing = generate(sprites_on_disk, db_lookup)

    # ── write sprite_lookup.c ───────────────────────────────────
    out_path = 'source/sprite_lookup.c'
    os.makedirs('source', exist_ok=True)
    with open(out_path, 'w') as f:
        f.write(content)

    print(f"✅ Generated: {out_path}")
    print(f"   Total entries: {entry_count}")
    print()

    # ── update sprite_lookup.h ──────────────────────────────────
    h_path = 'include/sprite_lookup.h'
    if os.path.exists(h_path):
        with open(h_path, 'r') as f:
            h_content = f.read()

        h_content = re.sub(
            r'#define SPRITE_LOOKUP_SIZE\s+\d+',
            f'#define SPRITE_LOOKUP_SIZE {entry_count}',
            h_content
        )

        with open(h_path, 'w') as f:
            f.write(h_content)

        print(f"✅ Updated: {h_path}")
        print(f"   SPRITE_LOOKUP_SIZE = {entry_count}")
    else:
        print(f"⚠️  {h_path} not found — update SPRITE_LOOKUP_SIZE manually to {entry_count}")

    # ── report missing ──────────────────────────────────────────
    if missing:
        print()
        print(f"⚠️  {len(missing)} sprites on disk but NOT in pokemon_database.c:")
        for m in missing:
            print(f"   - {m}")
        print("   These are included in the lookup but marked as 'Unknown'.")
        print("   You may want to add them to pokemon_database.c later.")

    print()
    print("📝 Next: Run 'make clean && make' to rebuild")
    print("=" * 60)


if __name__ == "__main__":
    main()
